// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdplujhwfwomluvfzapl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcGx1amh3ZndvbWx1dmZ6YXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDI3NDcsImV4cCI6MjA2NzMxODc0N30.GabFf78QfW5RP1G4sIa48ICfEemgF6bjVyJ0sJP_EUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});